### ISSUE TITLE
set `mappings = nil` could not disable the kemaps

### ISSUE THREAD

**Issue by meijieru** [ruifm/gitlinker.nvim#48]
**Describe the bug**
As the title, [here](https://github.com/ruifm/gitlinker.nvim/blob/bcfb3a07f57d131ad2cfe720c9ee551ece4086be/lua/gitlinker/mappings.lua#L20) overrides the mappings.

**Comment by ajitid** [comment]
Looks like resolving this would result in a breaking API change. If `nil` is fixed, we would have to remove the default mapping (which may or may not be desirable).

https://github.com/ruifm/gitlinker.nvim/blob/d28028ba21e8be2d9f290ba69eb08f96a31fa769/lua/gitlinker/mappings.lua#L20

**Comment by ajitid** [comment]
Or use `mappings` as `false` to remove mappings but `nil` (which equates to not defining a mapping through options) to use the default one?

**Comment by ruifm** [comment]
> Or use `mappings` as `false` to remove mappings but `nil` (which equates to not defining a mapping through options) to use the default one?

Sounds like the best option.

I think it was a mistake to auto define mappings. I did it to improve the out-of-the-box experience but now I don't think it's such a good idea and whatever is done will definitely break the API :cry:

**Comment by ajitid** [comment]
> I think it was a mistake to auto define mappings. 

It's feels worse to be blunt, but yes, for a single that won't be often by users, having a predefined mapping wasn't a good idea. 

> whatever is done will definitely break the API 

Kind of. If `nil` wasn't working for them, and nobody cared to raise an issue about it, it means people rarely considered nullifying gitlinker mappings. So not a huge user base would be affected. 

Would you mind taking a PR for this issue?

--- 

Unrelated. but in [one of the issue](https://github.com/ruifm/gitlinker.nvim/issues/29#issuecomment-1035330020) I became aware that one cannot give a range through command prompt as the plugin doesn't relies on `<` and `>` marks. Was this intended or should I create an issue?

**Comment by linrongbin16** [comment]
Submit #77, use "" (empty string) to disable default mappings.

**Comment by linrongbin16** [comment]
Hi @meijieru , @ajitid ,
I have fixed this issue in my fork with PR: https://github.com/linrongbin16/gitlinker.nvim/pull/1
Feel free to use it.

**Comment by ajitid** [comment]
I've already forked and am using a [different method](https://github.com/ajitid/gitlinker.nvim/blob/fix/mapping/lua/gitlinker/mappings.lua#L20-L22) to suppress mappings. 
Thanks for mentioning it anyway!

**Comment by linrongbin16** [comment]
Cool, I have also fixed another issue #75  (open browser in windows).
I use `cmd /C start {url}`. this method is copied from: https://github.com/axieax/urlview.nvim/blob/main/lua/urlview/actions.lua#L38.

**Comment by ArchitBhonsle** [comment]
So what's the status for this? Noticed that I still had the default mappings even though I set `mappings = nil`

**Comment by linrongbin16** [comment]
Hi all, I have make my own fork: https://github.com/linrongbin16/gitlinker.nvim.

It fixed this issue, and also support Windows, and refactored a lot of things, I believe it's much better.

**Comment by unphased** [comment]
can we standardize on @linrongbin16's plugin or what is everyone doing? I need `<Leader>g` for something else and i need to get rid of the input pause waiting for the `y`, but it's ridiculous that it's taken me an hour to figure out why the config to tell the plugin not to set a mapping is not working.

**Comment by unphased** [comment]
update: i had to switch back from the lingrongbin16 fork of this plugin because it broke recently and this plugin is not broken, but the inability to disable the default keybinding is still an issue.

**Comment by linrongbin16** [comment]
hi @unphased , can you give some configs to reproduce the broke issue on my gitlinker? Thanks
